# Create a service for Energi node
apiVersion: v1
kind: Service
metadata:
  name: energi-node
  labels:
    app: energi
spec:
  ports:
    - port: 39797
      name: energi
  clusterIP: None
  selector:
    app: energi
---
# create a statefulset for energi container image with persitent volume
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: energi-node-set
spec:
  serviceName: "energi"
  replicas: 3
  selector:
    matchLabels:
      app: energi
  template:
    metadata:
      labels:
        app: energi
    spec:
      containers:
        - name: energi-node
          image: energi-node:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 39797
              name: energi
          volumeMounts:
            - name: energi-store
              mountPath: /var/lib/energi
  volumeClaimTemplates:
    - metadata:
        name: energi-store
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
